---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gopneeqq/public_html/
    - export BACKUP_DIR="/tmp/backup_$(date +%Y%m%d_%H%M%S)"
    - mkdir -p $BACKUP_DIR
    - cp -r $DEPLOYPATH/* $BACKUP_DIR/ 2>/dev/null || true
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage/app $DEPLOYPATH/storage/ 2>/dev/null || true
    - /bin/cp -R storage/framework $DEPLOYPATH/storage/ 2>/dev/null || true
    - /bin/cp .env.example $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH 2>/dev/null || true
    - find $DEPLOYPATH -type f -exec chmod 644 {} \; 2>/dev/null || true
    - find $DEPLOYPATH -type d -exec chmod 755 {} \; 2>/dev/null || true
    - chmod -R 755 $DEPLOYPATH/storage
    - chmod -R 755 $DEPLOYPATH/bootstrap/cache
    - chmod 755 $DEPLOYPATH/artisan
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader --no-interaction 2>/dev/null || echo "Composer not available"
    - cd $DEPLOYPATH && [ ! -f .env ] && cp .env.example .env || true
    - cd $DEPLOYPATH && php artisan key:generate --no-interaction 2>/dev/null || echo "Please set APP_KEY manually"
    - cd $DEPLOYPATH && npm install 2>/dev/null || echo "NPM not available"
    - cd $DEPLOYPATH && npm run build 2>/dev/null || echo "Build assets manually"
    - cd $DEPLOYPATH && php artisan config:clear 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan cache:clear 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan route:clear 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan view:clear 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan config:cache 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan route:cache 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan view:cache 2>/dev/null || true
    - cd $DEPLOYPATH && php artisan storage:link 2>/dev/null || true
    - chmod -R 755 $DEPLOYPATH/storage
    - chmod -R 755 $DEPLOYPATH/bootstrap/cache
